# This docker compose file can be used to start up a statemodify notebook locally
# for testing.
services:
  notebook:
    container_name: jupyter-notebook-gcam-tuner-notebook
    build:
      context: .
      dockerfile: Dockerfile
      target: gcam_tuner_deploy
    image: ghcr.io/msd-live/jupyter/jupyter-notebook-gcam-tuner-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/data
      - ./data:/data
      - ./notebooks:/home/jovyan/notebooks
